### ISSUE TITLE
mqtt.zen... no values anymore

### ISSUE THREAD

**Issue by agrdbf** [Zendure/developer-device-data-report#22]
Since 10 a.m. CEST I don't get any values from mqtt.zen-iot.com anymore. Everything was running the last week without problems.
![image](https://github.com/Zendure/developer-device-data-report/assets/87203939/9a0d7c76-a882-4bdf-90d9-381ba4693904)

Can reproduce that via mqtt-Explorer, I can connect, but get nothing.

Has somebody else the same issue? Is something known about that?

**Comment by Stephan23579** [comment]
I have the same issue. Connection OK, but Receiving no messages.

**Comment by agrdbf** [comment]
> I have the same issue. Connection OK, but Receiving no messages.

good to know. Thanks for your reply.

**Comment by Zendure** [comment]
I apologize for the inconvenience you're experiencing. After investigating
the issue, we found that there has been a surge in device messages leading
to message accumulation on the server. However, please rest assured that we
have taken measures to scale up and resolve this problem.

We sincerely apologize for any inconvenience caused and appreciate your
patience during this time. If you have any other questions or need further
assistance, please don't hesitate to contact us. We are committed to
providing you with excellent service.

Once again, we apologize for any inconvenience caused.

Wishing you a pleasant user experience!

Best regards Zendure Developer Team

agrdbf ***@***.***> 于2023年7月17日周一 19:28写道：

**Comment by agrdbf** [comment]
> I apologize for the inconvenience you're experiencing. After investigating the issue, we found that there has been a surge in device messages leading to message accumulation on the server. However, please rest assured that we have taken measures to scale up and resolve this problem. We sincerely apologize for any inconvenience caused and appreciate your patience during this time. If you have any other questions or need further assistance, please don't hesitate to contact us. We are committed to providing you with excellent service. Once again, we apologize for any inconvenience caused. Wishing you a pleasant user experience! Best regards Zendure Developer Team

Hi, looks better now. Values from mqtt are coming in again. Thanks for solving the problem that quick!

**Comment by agrdbf** [comment]
Issue is solved, can be closed.

**Comment by jsuelwald** [comment]
Re-opening the issue, becuase doesn't work here right now; neither with mqtt as bridge nor mit mqtt explorer

**Comment by z-master42** [comment]
Can also confirm that it works again. And the update of the values is much faster than before.

**Comment by z-master42** [comment]
The AppKey ist your username. The AppSecret ist your Password.

**Comment by jsuelwald** [comment]
Ok, sorry - i've got that setup that way - still doesn't work

**Comment by jsuelwald** [comment]
<img width="950" alt="image" src="https://github.com/Zendure/developer-device-data-report/assets/2499585/de919f71-197a-4af5-9eee-ae2837ea6c24">

As shown here - worked fine until then..

**Comment by z-master42** [comment]
That's crazy. For me, as for everyone else, it stopped working from the same time. But since this afternoon it runs again, as per the Zendure post above.

**Comment by jsuelwald** [comment]
Yeah, but here it doesn't and i've got not way to debug that further -.-

**Comment by jsuelwald** [comment]
I think i'll wait until the SOlar Flow Module offers it's data locally via MQTT as well, i hate using an external data source.

**Comment by agrdbf** [comment]
> I think i'll wait until the SOlar Flow Module offers it's data locally via MQTT as well, i hate using an external data source.

Have you set your subscription to AppKey/# ? (in mqtt explorer in the advanced section)

**Comment by jsuelwald** [comment]
Yeah, yesterday it didn't work at all.

Now it works a bit. Gets data and disconnects again
<img width="300" alt="image" src="https://github.com/Zendure/developer-device-data-report/assets/2499585/9c2f60ac-dc59-4784-9da8-a5fb561fce79">

MQTT-Broker on Home Assistant is configured as follows:

```connection external-bridge
address mqtt.zen-iot.com:1883
remote_username <snip>
remote_password <snipsnipsnip>
clientid zendure

topic <snip>/# both 0 zend/
```
And i didn't touch that config for days, because it was working fine.

**Comment by agrdbf** [comment]
I do not use home assistant for that, but from config side it looks good to me. I'm using a similar config with nodered.
But maybe try a more generic clientid. I'm not sure and I'm not a mqtt pro, but I've something in mind that the client-id has to be unique for the whole broker and in the past with the ecoflow mqtt server that was a common issue, when multiple users uses the same clientid.

**Comment by z-master42** [comment]
Isn't it then the exact opposite? A more specific clientid? Try remote_clientid <snip> instead.

**Comment by jsuelwald** [comment]
Suddenly, as of 21:00 yesterday (CEST) it works again without me changing anything. I can't rule out as issue with internet routing and/or DNS because i didn't think of that as a possible fault at this time.

**Comment by agrdbf** [comment]
Looks like the issue occurs again. Since yesterday somewhen in the evening, I don't get values anymore. Looks exactly the same like the last time. Connection to mqtt-zen-iot.com is possible, but no values. Am I the only one or can anybody else confirm?

**Comment by DeathForce07** [comment]
> Looks like the issue occurs again. Since yesterday somewhen in the evening, I don't get values anymore. Looks exactly the same like the last time. Connection to mqtt-zen-iot.com is possible, but no values. Am I the only one or can anybody else confirm?

same here

**Comment by Psyle80** [comment]
same here

**Comment by HHoppenstock** [comment]
same here

**Comment by agrdbf** [comment]
Since 2:30 p.m. it seems to be fixed, since then I get values again

**Comment by achi87** [comment]
Nothing again as far as I can see (last 6/7 hours)

**Comment by agrdbf** [comment]
Looks like we have the same issue again. Don't get any values from zendures mqtt since 2 hours. :/
